services:
  postgres:
    container_name: db-airgoda
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:5432

  redis:
    container_name: cache-airgoda
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

volumes:
  postgres:
  redis: